### ISSUE TITLE
ceilometer-customize role needs to be updated to support PF9 v3.8+

### ISSUE THREAD

**Issue by mmccarre** [platform9/express#183]
Ceilometer configuration files are changing in v3.8+. This role needs to be updated to support the latest.

**Comment by mmccarre** [comment]
Also address issue #122 during this change.

New destination for the file should be `/opt/pf9/etc/ceilometer/polling.yaml`

Content may look like:
```
---
sources:
    - name: pf9_vm_pollsters
      interval: 180
      meters:
        - cpu

    - name: pf9_host_pollsters
      interval: 300
      meters:
        - pf9.host.cpu.usage
        - pf9.host.memory.usage
        - pf9.host.root.disk.usage
        - pf9.host.instance.disk.usage
```
