### ISSUE TITLE
Remove -d flag from libvirtd_opts in /etc/default/libvirt-bin on non Ubuntu 14.04 hosts

### ISSUE THREAD

**Issue by bpyros** [platform9/express#203]
##### SUMMARY

libvirt-bin does not support -d flag in Ubuntu 16.04

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
libvirt configuration for ./roles/secure-live-migration 

##### ANSIBLE VERSION

```
N/A
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Ubuntu 16.04 managed hosts

##### STEPS TO REPRODUCE

Deploy an Ubuntu 16.04 host either with the -a flag to automatically authorize or run:

`./pf9-express -b -a -t live-migration hypervisors`

```
.roles/secure-live-migration/tasks/configure.yaml has the following:

- name: Tell libvirt to listen on startup - Ubuntu
  lineinfile:
    state: present
    create: True
    line: 'libvirtd_opts="-d -l"'
    dest: /etc/default/libvirt-bin
    regexp: '^#?libvirtd_opts=*.*$'
  tags:
    - live-migration
  when: ansible_distribution == "Ubuntu"
  notify: restart libvirtd

This creates the following in /etc/default/libvirt-bin

# Defaults for libvirtd initscript (/etc/init.d/libvirtd)
# This is a POSIX shell fragment

# Start libvirtd to handle qemu/kvm:
start_libvirtd="yes"

# options passed to libvirtd, add "-l" to listen on tcp
#libvirtd_opts=""
libvirtd_opts="-d -l"

# pass in location of kerberos keytab
#export KRB5_KTNAME=/etc/libvirt/libvirt.keytab

# Whether to mount a systemd like cgroup layout (only
# useful when not running systemd)
#mount_cgroups=yes
# Which cgroups to mount
#cgroups="memory devices"
```

##### EXPECTED RESULTS

libvirt-bin starts successfully

##### ACTUAL RESULTS

libvirt-bin exits

```
# systemctl status libvirt-bin.service
● libvirt-bin.service - Virtualization daemon
   Loaded: loaded (/lib/systemd/system/libvirt-bin.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2019-03-27 17:03:28 UTC; 11s ago
     Docs: man:libvirtd(8)
           http://libvirt.org
  Process: 3704 ExecStart=/usr/sbin/libvirtd $libvirtd_opts (code=exited, status=0/SUCCESS)
 Main PID: 3704 (code=exited, status=0/SUCCESS)
    Tasks: 20
   Memory: 5.8M
      CPU: 11.565s
   CGroup: /system.slice/libvirt-bin.service
           ├─3672 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
           ├─3673 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
           ├─3706 /usr/sbin/libvirtd -d
           └─3735 /usr/sbin/libvirtd -d

Mar 27 17:03:28 16 systemd[1]: Stopped Virtualization daemon.
Mar 27 17:03:28 16 systemd[1]: Starting Virtualization daemon...
Mar 27 17:03:28 16 systemd[1]: Started Virtualization daemon.
```

While libvirt does function, this state will cause host upgrades to fail as libvirt-bin is in an inactive state as the -d flag is no longer valid in Ubuntu 16.04. This is a known issue:

https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1567272
