### ISSUE TITLE
Multipath packages don't get installed on Ubuntu 16.04 hosts

### ISSUE THREAD

**Issue by piyush271291** [platform9/express#257]
##### SUMMARY
Multipath packages don't get installed on Ubuntu 16.04 hosts
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME
Multipath module

##### ANSIBLE VERSION

```
ansible 2.9.2
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### OS / ENVIRONMENT
 cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
l##### STEPS TO REPRODUCE

running pf9-express with autoregister switch results in the following multipath roles to fail 

This is because ubuntu.yml for this role does nothing. 

```yaml
---
- name: Check if pf9-ostackhost in installed (Ubuntu)
  shell: "`which dpkg-query` -s pf9-ostackhost > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: pkg_state_ostackhost_ubuntu
  when:
    - ansible_pkg_mgr == "apt"

- debug: msg="running multipath/tasks/ubuntu.yml"
```

##### EXPECTED RESULTS

The multipath task to complete successfully for the ubuntu host and service getting started. 
##### ACTUAL RESULTS

```TASK [multipath : enable multipathd] ******************************************************************************************************************************************************************************
Friday 31 January 2020  16:43:43 +0100 (0:00:00.565)       0:06:43.584 ********
fatal: [hv02]: FAILED! => {"changed": false, "msg": "Could not find the requested service multipathd: host"}
```
